version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies ..."
      - npm install # 종속성 설치
  build:
    command:
      - echo "Build Started on `date`"
      - npm run build # Next.js 앱 빌드
artifacts:
  files:
    - '**/*' # 빌드된 모든 파일을 아카이브
  base-directry:
    - out
cache:
  paths:
    - 'node_modules/**/*' # 종속성 캐싱
